import AppKit
import Combine

struct Clip: Codable, Identifiable, Equatable {
    var id = UUID()
    var text: String?
    var image: Data?
    var date = Date()
    var source: String
    var pinned = false
    var title: String { text ?? "Image" }
    var symbol: String { image != nil ? "photo" : (text?.hasPrefix("https://") == true ? "link" : "text.alignleft") }
}

final class History: ObservableObject {
    @Published var clips: [Clip] = []
    @Published var paused = false
    @Published var error: String?
    @Published var limit: Int { didSet { UserDefaults.standard.set(limit, forKey: "historyLimit"); trim(); save() } }
    @Published var excludedApps: String { didSet { UserDefaults.standard.set(excludedApps, forKey: "excludedApps") } }
    private var timer: Timer?
    private var changeCount: Int
    private let pasteboard: NSPasteboard
    private let file: URL
    static let ignoredTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]

    init(file: URL? = nil, pasteboard: NSPasteboard = .general, monitoring: Bool = true) {
        self.pasteboard = pasteboard
        self.changeCount = pasteboard.changeCount
        self.file = file ?? FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("CopyCat/history.json")
        limit = UserDefaults.standard.object(forKey: "historyLimit") as? Int ?? 200
        excludedApps = UserDefaults.standard.string(forKey: "excludedApps") ?? ""
        if FileManager.default.fileExists(atPath: self.file.path) {
            do { clips = try JSONDecoder().decode([Clip].self, from: Data(contentsOf: self.file)) }
            catch { self.error = "History could not be loaded: \(error.localizedDescription)" }
        }
        if monitoring {
            timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        }
    }
    deinit { timer?.invalidate() }

    func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard !paused else { return }
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        let app = NSWorkspace.shared.frontmostApplication
        let exclusions = excludedApps.components(separatedBy: .newlines).map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        guard !exclusions.contains(app?.bundleIdentifier ?? "") else { return }
        let source = app?.localizedName ?? "Unknown app"
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            guard text.utf8.count <= 2_000_000 else { return }
            add(Clip(text: text, source: source))
        } else if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), data.count <= 10_000_000 {
            add(Clip(image: data, source: source))
        }
    }
    func add(_ clip: Clip) {
        var next = clip
        if let old = clips.first(where: { $0.text == clip.text && $0.image == clip.image }) {
            next.id = old.id
            next.pinned = old.pinned
            clips.removeAll { $0.id == old.id }
        }
        clips.insert(next, at: 0)
        trim()
        save()
    }
    func trim() {
        var count = 0
        clips = clips.filter { clip in
            if clip.pinned { return true }
            count += 1
            return count <= limit
        }
    }
    func filtered(_ query: String, pinnedOnly: Bool = false) -> [Clip] {
        clips.filter { (!pinnedOnly || $0.pinned) && (query.isEmpty || $0.title.localizedCaseInsensitiveContains(query) || $0.source.localizedCaseInsensitiveContains(query)) }
            .sorted { a, b in a.pinned != b.pinned ? a.pinned : a.date > b.date }
    }
    func copy(_ clip: Clip) {
        pasteboard.clearContents()
        if let text = clip.text { pasteboard.setString(text, forType: .string) }
        else if let data = clip.image, let image = NSImage(data: data) { pasteboard.writeObjects([image]) }
        changeCount = pasteboard.changeCount
    }
    func pin(_ clip: Clip) {
        guard let index = clips.firstIndex(where: { $0.id == clip.id }) else { return }
        clips[index].pinned.toggle()
        trim()
        save()
    }
    func remove(_ clip: Clip) { clips.removeAll { $0.id == clip.id }; save() }
    func clear() { clips.removeAll { !$0.pinned }; save() }
    private func save() {
        do {
            try FileManager.default.createDirectory(at: file.deletingLastPathComponent(), withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
            try JSONEncoder().encode(clips).write(to: file, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: file.path)
        } catch { self.error = "History could not be saved: \(error.localizedDescription)" }
    }
}
